# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - configs/config.yaml
      - src/utils/common.py
      - src/utils/data_mgmt.py
    params:
      - prepare.split
      - prepare.seed
    outs:
      - artifacts/prepared/test.tsv
      - artifacts/prepared/train.tsv
  
  featurize:
    cmd: python src/stage_02_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_featurization.py
      - artifacts/prepared/test.tsv
      - artifacts/prepared/train.tsv
      - configs/config.yaml
      - src/utils/common.py
      - src/utils/featurize.py
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl
    
  train:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/features/train.pkl
      - configs/config.yaml
      - src/utils/common.py
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python src/stage_04_evaluate.py --config=configs/config.yaml
    deps:
      - src/stage_04_evaluate.py
      - artifacts/features/test.pkl
      - artifacts/model/model.pkl
      - configs/config.yaml
      - src/utils/common.py
    metrics:
      - scores.json:
          cache: False
    plots: 
      - prc.json:
          cache: False
          x: recall
          y: precision
      - roc.json:
          cache: False
          x: fpr
          y: tpr
  run_plots_command:
    cmd: dvc plots diff
