# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - configs/config.yaml
      - src/utils/common.py
      - src/utils/data_mgmt.py
    params:
      - prepare.split
      - prepare.seed
    outs:
      - artifacts/prepared/test.tsv
      - artifacts/prepared/train.tsv
